apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v260123-6b19cba.cowboys.wildwest.platform-mesh.io
spec:
  group: wildwest.platform-mesh.io
  names:
    kind: Cowboy
    listKind: CowboyList
    plural: cowboys
    singular: cowboy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.intent
      name: Intent
      type: string
    - jsonPath: .status.result
      name: Result
      type: string
    name: v1alpha1
    schema:
      description: Cowboy is the Schema for the cowboys API
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: CowboySpec defines the desired state of Cowboy
          properties:
            intent:
              description: Intent is the desired action for the cowboy
              type: string
          type: object
        status:
          description: CowboyStatus defines the observed state of Cowboy
          properties:
            result:
              description: Result is the outcome of the cowboy's action
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
