apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
    ui.platform-mesh.io/content-for: wildwest.platform-mesh.io
  name: cowboys-ui
spec:
  inlineConfiguration:
    content: |-
     {
      "name": "cowboys",
      "luigiConfigFragment": {
        "data": {
          "nodes": [
            {
              "pathSegment": "cowboys",
              "label": "Cowboys",
              "hideFromNav": false,
              "icon": "person-placeholder",
              "url": "http://localhost:4200/index.html",
              "entityType": "main.core_platform-mesh_io_account",
              "order": 900,
              "loadingIndicator": {
                "enabled": true
              },
              "context": {
                "accountId": ":core_platform-mesh_io_accountId"
              }
            }
          ]
        }
      }
     }
    contentType: json