apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
    ui.platform-mesh.io/content-for: wildwest.platform-mesh.io
  name: cowboys-ui
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "cowboys",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "pathSegment": "ur-path-segment",
                "label": "My Microfrontend",
                "hideFromNav": false,
                "icon": "lab",
                "url": "http://localhost:8080/index.html",
                "urlSuffix": "/index.html",
                "entityType": "main",
                "loadingIndicator": {
                  "enabled": true
                }
              }
            ]
          }
        }
      }
    contentType: json