apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wildwest-apiexport-bind
rules:
  - apiGroups: ["apis.kcp.io"]
    resources: ["apiexports"]
    verbs: ["bind"]
    resourceNames: ["wildwest.platform-mesh.io"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wildwest-anonymous-bind
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: wildwest-apiexport-bind
  apiGroup: rbac.authorization.k8s.io
