apiVersion: v1
kind: Secret
metadata:
  name: wildwest-controller-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: wildwest-controller
type: kubernetes.io/service-account-token
